version: '2.2'

services:
  # Mongo replica sets (2) with 2 mongod instances each
  mongorsn1:
    build: shard
    command: mongod --shardsvr --replSet mongors1 --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - /mongo_cluster/data1:/data/db
    networks:
      - backend
  mongorsn2:
    build: shard
    command: mongod --shardsvr --replSet mongors1 --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    ports:
      - "127.0.0.1:27019:27017"
    volumes:
      - /mongo_cluster/data2:/data/db
    networks:
      - backend
  mongorsn3:
    build: shard
    command: mongod --shardsvr --replSet mongors2 --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    ports:
      - "127.0.0.1:27020:27017"
    volumes:
      - /mongo_cluster/data3:/data/db
    networks:
      - backend
  mongorsn4:
    build: shard
    command: mongod --shardsvr --replSet mongors2 --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    ports:
      - "127.0.0.1:27021:27017"
    volumes:
      - /mongo_cluster/data4:/data/db
    networks:
      - backend
  # 2 Mongo config servers
  mongocfg1:
    build: config
    command: mongod --configsvr --replSet mongors1conf --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/config1:/data/db
    networks:
      - backend
  mongocfg2:
    build: config
    command: mongod --configsvr --replSet mongors1conf --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/config2:/data/db
    networks:
      - backend
  mongocfg3:
    build: config
    command: mongod --configsvr --replSet mongors1conf --keyFile /tmp/mongodb-keyfile --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/config3:/data/db
    networks:
      - backend
  # Mongo router
  mongorouter:
    build: router
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --keyFile /tmp/mongodb-keyfile --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --bind_ip_all --port 27017
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - backend

networks:
  backend:
    external: true