version: "2"

services:
  postgres:
    build: postgres/
    environment:
      - POSTGRES_USER=greenapperdba
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=groupomania
    ports:
      - "5432:5432"
  groupomania:
    image: groupomania:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    command: ["./wait-for-it.sh", "postgres:5432"]